// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { HorizontalRunnerAutoscalerArgs } from "./horizontalRunnerAutoscaler";
export type HorizontalRunnerAutoscaler = import("./horizontalRunnerAutoscaler").HorizontalRunnerAutoscaler;
export const HorizontalRunnerAutoscaler: typeof import("./horizontalRunnerAutoscaler").HorizontalRunnerAutoscaler = null as any;
utilities.lazyLoad(exports, ["HorizontalRunnerAutoscaler"], () => require("./horizontalRunnerAutoscaler"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:actions.summerwind.dev/v1alpha1:HorizontalRunnerAutoscaler":
                return new HorizontalRunnerAutoscaler(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "actions.summerwind.dev/v1alpha1", _module)
