// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { ProvisionerArgs } from "./provisioner";
export type Provisioner = import("./provisioner").Provisioner;
export const Provisioner: typeof import("./provisioner").Provisioner = null as any;
utilities.lazyLoad(exports, ["Provisioner"], () => require("./provisioner"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:karpenter.sh/v1alpha5:Provisioner":
                return new Provisioner(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "karpenter.sh/v1alpha5", _module)
