export const websitesDbMap = [
  [
    { name: "flirtytown", siteId: "4" },
    { name: "myflingmate", siteId: "5" },
    { name: "lustpals", siteId: "6" },
    { name: "follarico", siteId: "7" },
    { name: "jijneukt", siteId: "10" },
    { name: "geheimerfick", siteId: "13" },
    { name: "duknulla", siteId: "14" },
    { name: "geheimneuken", siteId: "16" },
    { name: "sexosecreto", siteId: "17" },
    { name: "mycrushfinder", siteId: "9" },
  ],
  [
    { name: "mysecretfeels", siteId: "19" },
    { name: "loversnextdoor", siteId: "20" },
    { name: "deliamigos", siteId: "21" },
    { name: "pourjouir", siteId: "22" },
    { name: "ragazzevicino", siteId: "23" },
    { name: "bangtender", siteId: "24" },
    { name: "meltingme", siteId: "25" },
    { name: "spicywives", siteId: "26" },
    { name: "rabbitsmeet", siteId: "27" },
    { name: "horneyfriends", siteId: "28" },
    { name: "myjuicycrush", siteId: "29" },
  ],
  [{ name: "shag2night", siteId: "1" }],
  [{ name: "flingpals", siteId: "2" }],
  [{ name: "yummyaffair", siteId: "3" }],
  [{ name: "aussiebang", siteId: "15" }],
  [{ name: "seekingcrush", siteId: "8" }],
  [{ name: "ilsessuali", siteId: "11" }],
  [{ name: "honeynearby", siteId: "18" }],
  [{ name: "laissebaiser", siteId: "12" }],
];
