// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * Canary is the Schema for the Canary API.
 */
export class Canary extends pulumi.CustomResource {
    /**
     * Get an existing Canary resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Canary {
        return new Canary(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:flagger.app/v1beta1:Canary';

    /**
     * Returns true if the given object is an instance of Canary.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Canary {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Canary.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"flagger.app/v1beta1" | undefined>;
    public readonly kind!: pulumi.Output<"Canary" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * CanarySpec defines the desired state of a Canary.
     */
    public readonly spec!: pulumi.Output<outputs.flagger.v1beta1.CanarySpec | undefined>;
    /**
     * CanaryStatus defines the observed state of a canary.
     */
    public readonly status!: pulumi.Output<outputs.flagger.v1beta1.CanaryStatus | undefined>;

    /**
     * Create a Canary resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CanaryArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "flagger.app/v1beta1";
            resourceInputs["kind"] = "Canary";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Canary.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Canary resource.
 */
export interface CanaryArgs {
    apiVersion?: pulumi.Input<"flagger.app/v1beta1">;
    kind?: pulumi.Input<"Canary">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * CanarySpec defines the desired state of a Canary.
     */
    spec?: pulumi.Input<inputs.flagger.v1beta1.CanarySpecArgs>;
    /**
     * CanaryStatus defines the observed state of a canary.
     */
    status?: pulumi.Input<inputs.flagger.v1beta1.CanaryStatusArgs>;
}
