// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import {ObjectMeta} from "../meta/v1";

export namespace monitoring {
    export namespace v1alpha1 {
        /**
         * Spec holds the specification of the desired behavior for the logs instance.
         */
        export interface LogsInstanceSpec {
            /**
             * AdditionalScrapeConfigs allows specifying a key of a Secret containing additional Grafana Agent logging scrape configurations. Scrape configurations specified are appended to the configurations generated by the Grafana Agent Operator. 
             *  Job configurations specified must have the form as specified in the official Promtail documentation: 
             *  https://grafana.com/docs/loki/latest/clients/promtail/configuration/#scrape_configs 
             *  As scrape configs are appended, the user is responsible to make sure it is valid. Note that using this feature may expose the possibility to break upgrades of Grafana Agent. It is advised to review both Grafana Agent and Promtail release notes to ensure that no incompatible scrape configs are going to break Grafana Agent after the upgrade.
             */
            additionalScrapeConfigs?: outputs.monitoring.v1alpha1.LogsInstanceSpecAdditionalscrapeconfigs;
            /**
             * Clients controls where logs are written to for this instance.
             */
            clients?: outputs.monitoring.v1alpha1.LogsInstanceSpecClients[];
            /**
             * Set of labels to determine which namespaces should be watched for PodLogs. If not provided, checks only namespace of the instance.
             */
            podLogsNamespaceSelector?: outputs.monitoring.v1alpha1.LogsInstanceSpecPodlogsnamespaceselector;
            /**
             * Determines which PodLogs should be selected for including in this instance.
             */
            podLogsSelector?: outputs.monitoring.v1alpha1.LogsInstanceSpecPodlogsselector;
            /**
             * Configures how tailed targets are watched.
             */
            targetConfig?: outputs.monitoring.v1alpha1.LogsInstanceSpecTargetconfig;
        }

        /**
         * AdditionalScrapeConfigs allows specifying a key of a Secret containing additional Grafana Agent logging scrape configurations. Scrape configurations specified are appended to the configurations generated by the Grafana Agent Operator. 
         *  Job configurations specified must have the form as specified in the official Promtail documentation: 
         *  https://grafana.com/docs/loki/latest/clients/promtail/configuration/#scrape_configs 
         *  As scrape configs are appended, the user is responsible to make sure it is valid. Note that using this feature may expose the possibility to break upgrades of Grafana Agent. It is advised to review both Grafana Agent and Promtail release notes to ensure that no incompatible scrape configs are going to break Grafana Agent after the upgrade.
         */
        export interface LogsInstanceSpecAdditionalscrapeconfigs {
            /**
             * The key of the secret to select from.  Must be a valid secret key.
             */
            key: string;
            /**
             * Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?
             */
            name?: string;
            /**
             * Specify whether the Secret or its key must be defined
             */
            optional?: boolean;
        }

        /**
         * LogsClientSpec defines the client integration for logs, indicating which Loki server to send logs to.
         */
        export interface LogsInstanceSpecClients {
            /**
             * Configures how to retry requests to Loki when a request fails. Defaults to a minPeriod of 500ms, maxPeriod of 5m, and maxRetries of 10.
             */
            backoffConfig?: outputs.monitoring.v1alpha1.LogsInstanceSpecClientsBackoffconfig;
            /**
             * BasicAuth for the Loki server.
             */
            basicAuth?: outputs.monitoring.v1alpha1.LogsInstanceSpecClientsBasicauth;
            /**
             * Maximum batch size (in bytes) of logs to accumulate before sending the batch to Loki.
             */
            batchSize?: number;
            /**
             * Maximum amount of time to wait before sending a batch, even if that batch isn't full.
             */
            batchWait?: string;
            /**
             * BearerToken used for remote_write.
             */
            bearerToken?: string;
            /**
             * BearerTokenFile used to read bearer token.
             */
            bearerTokenFile?: string;
            /**
             * ExternalLabels are labels to add to any time series when sending data to Loki.
             */
            externalLabels?: {[key: string]: string};
            /**
             * ProxyURL to proxy requests through. Optional.
             */
            proxyUrl?: string;
            /**
             * Tenant ID used by default to push logs to Loki. If omitted assumes remote Loki is running in single-tenant mode or an authentication layer is used to inject an X-Scope-OrgID header.
             */
            tenantId?: string;
            /**
             * Maximum time to wait for a server to respond to a request.
             */
            timeout?: string;
            /**
             * TLSConfig to use for the client. Only used when the protocol of the URL is https.
             */
            tlsConfig?: outputs.monitoring.v1alpha1.LogsInstanceSpecClientsTlsconfig;
            /**
             * URL is the URL where Loki is listening. Must be a full HTTP URL, including protocol. Required. Example: https://logs-prod-us-central1.grafana.net/loki/api/v1/push.
             */
            url: string;
        }

        /**
         * Configures how to retry requests to Loki when a request fails. Defaults to a minPeriod of 500ms, maxPeriod of 5m, and maxRetries of 10.
         */
        export interface LogsInstanceSpecClientsBackoffconfig {
            /**
             * Maximum backoff time between retries.
             */
            maxPeriod?: string;
            /**
             * Maximum number of retries to perform before giving up a request.
             */
            maxRetries?: number;
            /**
             * Initial backoff time between retries. Time between retries is increased exponentially.
             */
            minPeriod?: string;
        }

        /**
         * BasicAuth for the Loki server.
         */
        export interface LogsInstanceSpecClientsBasicauth {
            /**
             * The secret in the service monitor namespace that contains the password for authentication.
             */
            password?: outputs.monitoring.v1alpha1.LogsInstanceSpecClientsBasicauthPassword;
            /**
             * The secret in the service monitor namespace that contains the username for authentication.
             */
            username?: outputs.monitoring.v1alpha1.LogsInstanceSpecClientsBasicauthUsername;
        }

        /**
         * The secret in the service monitor namespace that contains the password for authentication.
         */
        export interface LogsInstanceSpecClientsBasicauthPassword {
            /**
             * The key of the secret to select from.  Must be a valid secret key.
             */
            key: string;
            /**
             * Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?
             */
            name?: string;
            /**
             * Specify whether the Secret or its key must be defined
             */
            optional?: boolean;
        }

        /**
         * The secret in the service monitor namespace that contains the username for authentication.
         */
        export interface LogsInstanceSpecClientsBasicauthUsername {
            /**
             * The key of the secret to select from.  Must be a valid secret key.
             */
            key: string;
            /**
             * Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?
             */
            name?: string;
            /**
             * Specify whether the Secret or its key must be defined
             */
            optional?: boolean;
        }

        /**
         * TLSConfig to use for the client. Only used when the protocol of the URL is https.
         */
        export interface LogsInstanceSpecClientsTlsconfig {
            /**
             * Struct containing the CA cert to use for the targets.
             */
            ca?: outputs.monitoring.v1alpha1.LogsInstanceSpecClientsTlsconfigCa;
            /**
             * Path to the CA cert in the Prometheus container to use for the targets.
             */
            caFile?: string;
            /**
             * Struct containing the client cert file for the targets.
             */
            cert?: outputs.monitoring.v1alpha1.LogsInstanceSpecClientsTlsconfigCert;
            /**
             * Path to the client cert file in the Prometheus container for the targets.
             */
            certFile?: string;
            /**
             * Disable target certificate validation.
             */
            insecureSkipVerify?: boolean;
            /**
             * Path to the client key file in the Prometheus container for the targets.
             */
            keyFile?: string;
            /**
             * Secret containing the client key file for the targets.
             */
            keySecret?: outputs.monitoring.v1alpha1.LogsInstanceSpecClientsTlsconfigKeysecret;
            /**
             * Used to verify the hostname for the targets.
             */
            serverName?: string;
        }

        /**
         * Struct containing the CA cert to use for the targets.
         */
        export interface LogsInstanceSpecClientsTlsconfigCa {
            /**
             * ConfigMap containing data to use for the targets.
             */
            configMap?: outputs.monitoring.v1alpha1.LogsInstanceSpecClientsTlsconfigCaConfigmap;
            /**
             * Secret containing data to use for the targets.
             */
            secret?: outputs.monitoring.v1alpha1.LogsInstanceSpecClientsTlsconfigCaSecret;
        }

        /**
         * ConfigMap containing data to use for the targets.
         */
        export interface LogsInstanceSpecClientsTlsconfigCaConfigmap {
            /**
             * The key to select.
             */
            key: string;
            /**
             * Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?
             */
            name?: string;
            /**
             * Specify whether the ConfigMap or its key must be defined
             */
            optional?: boolean;
        }

        /**
         * Secret containing data to use for the targets.
         */
        export interface LogsInstanceSpecClientsTlsconfigCaSecret {
            /**
             * The key of the secret to select from.  Must be a valid secret key.
             */
            key: string;
            /**
             * Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?
             */
            name?: string;
            /**
             * Specify whether the Secret or its key must be defined
             */
            optional?: boolean;
        }

        /**
         * Struct containing the client cert file for the targets.
         */
        export interface LogsInstanceSpecClientsTlsconfigCert {
            /**
             * ConfigMap containing data to use for the targets.
             */
            configMap?: outputs.monitoring.v1alpha1.LogsInstanceSpecClientsTlsconfigCertConfigmap;
            /**
             * Secret containing data to use for the targets.
             */
            secret?: outputs.monitoring.v1alpha1.LogsInstanceSpecClientsTlsconfigCertSecret;
        }

        /**
         * ConfigMap containing data to use for the targets.
         */
        export interface LogsInstanceSpecClientsTlsconfigCertConfigmap {
            /**
             * The key to select.
             */
            key: string;
            /**
             * Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?
             */
            name?: string;
            /**
             * Specify whether the ConfigMap or its key must be defined
             */
            optional?: boolean;
        }

        /**
         * Secret containing data to use for the targets.
         */
        export interface LogsInstanceSpecClientsTlsconfigCertSecret {
            /**
             * The key of the secret to select from.  Must be a valid secret key.
             */
            key: string;
            /**
             * Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?
             */
            name?: string;
            /**
             * Specify whether the Secret or its key must be defined
             */
            optional?: boolean;
        }

        /**
         * Secret containing the client key file for the targets.
         */
        export interface LogsInstanceSpecClientsTlsconfigKeysecret {
            /**
             * The key of the secret to select from.  Must be a valid secret key.
             */
            key: string;
            /**
             * Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?
             */
            name?: string;
            /**
             * Specify whether the Secret or its key must be defined
             */
            optional?: boolean;
        }

        /**
         * Set of labels to determine which namespaces should be watched for PodLogs. If not provided, checks only namespace of the instance.
         */
        export interface LogsInstanceSpecPodlogsnamespaceselector {
            /**
             * matchExpressions is a list of label selector requirements. The requirements are ANDed.
             */
            matchExpressions?: outputs.monitoring.v1alpha1.LogsInstanceSpecPodlogsnamespaceselectorMatchexpressions[];
            /**
             * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
             */
            matchLabels?: {[key: string]: string};
        }

        /**
         * A label selector requirement is a selector that contains values, a key, and an operator that relates the key and values.
         */
        export interface LogsInstanceSpecPodlogsnamespaceselectorMatchexpressions {
            /**
             * key is the label key that the selector applies to.
             */
            key: string;
            /**
             * operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
             */
            operator: string;
            /**
             * values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
             */
            values?: string[];
        }

        /**
         * Determines which PodLogs should be selected for including in this instance.
         */
        export interface LogsInstanceSpecPodlogsselector {
            /**
             * matchExpressions is a list of label selector requirements. The requirements are ANDed.
             */
            matchExpressions?: outputs.monitoring.v1alpha1.LogsInstanceSpecPodlogsselectorMatchexpressions[];
            /**
             * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
             */
            matchLabels?: {[key: string]: string};
        }

        /**
         * A label selector requirement is a selector that contains values, a key, and an operator that relates the key and values.
         */
        export interface LogsInstanceSpecPodlogsselectorMatchexpressions {
            /**
             * key is the label key that the selector applies to.
             */
            key: string;
            /**
             * operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
             */
            operator: string;
            /**
             * values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
             */
            values?: string[];
        }

        /**
         * Configures how tailed targets are watched.
         */
        export interface LogsInstanceSpecTargetconfig {
            /**
             * Period to resync directories being watched and files being tailed to discover new ones or stop watching removed ones.
             */
            syncPeriod?: string;
        }

    }
}
